---
title: "chapter-01-give-context-fast"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Chapter 1 - Give context fast

## Lesson 1 - A chart to start out with

```{r}

# carregar dados
penguins <- palmerpenguins::penguins |>
  dplyr::filter(!is.na(sex))

# plotar primeiro gráfico base
penguins |>
  # camada base
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  # camada geométrica
  ggplot2::geom_point(
    size = 3, # tamanho dos pontos
    alpha = 0.75, # opacidade dos pontos
    shape = 21, # tipo (tema) dos pontos
    color = 'black', # cor da borda dos pontos
    # garantir que os pontos sejam separados de acordo com o grupo específicado 
    # no 'fill' do mapping, o seed é só pra garantir a mesma disposição sempre
    position = ggplot2::position_jitterdodge(seed = 34543)
  )

```


## Lesson 2 - Make labels large enough

```{r}

penguins |>
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  ggplot2::geom_point(
    size = 3,
    alpha = 0.75,
    shape = 21,
    color = 'black',
    position = ggplot2::position_jitterdodge(seed = 34543)
  ) +
  # adicionando um tema preenchendo com o argumento base_size para garantir que
  # todo o texto do gráfico seja legível (aumentando o tamanho da fonte)
  ggplot2::theme_minimal(base_size = 16)

```



## Lesson 3 - Meaningful label names
```{r}
penguins |>
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  ggplot2::geom_point(
    size = 3,
    alpha = 0.75,
    shape = 21,
    color = "black",
    position = ggplot2::position_jitterdodge(seed = 34543)
  ) +
  ggplot2::theme_minimal(base_size = 16) +
  # adicionando títulos
  ggplot2::labs(
    x = ggplot2::element_blank(), # remover o título do eixo x
    y = "Comprimento do bico (em mm)", # eixo y
    fill = "Sexo", # legenda
    title = "Medições de diferentes espécies de pinguins" # título do gráfico
  )

```



## Lesson 4 - Meaningful label numbers
```{r}
penguins |>
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  ggplot2::geom_point(
    size = 3,
    alpha = 0.75,
    shape = 21,
    color = "black",
    position = ggplot2::position_jitterdodge(seed = 34543)
  ) +
  ggplot2::theme_minimal(base_size = 16) +
  ggplot2::labs(
    x = ggplot2::element_blank(),
    y = "Comprimento do bico",
    fill = "Sexo",
    title = "Medições de diferentes espécies de pinguins"
  ) +
  # alterar os dados da legenda, para esse caso os dados são 'discretos', ou seja, categorias
  ggplot2::scale_fill_discrete(
    # tranformar as labels da legenda para primeira letra maiúscula
    labels = \(x) stringr::str_to_title(x)
  ) +
  # alterar os dados do eixo y, para esse caso os dados são 'contínuos', ou seja,
  # números
  ggplot2::scale_y_continuous(
    # adicionar um sufixo nos números do eixo
    labels = scales::label_number(suffix = "mm")
  )

```




## Lesson 5 - Sort your chart elements
```{r}

# modificar dados
# carregar dados
penguins <- palmerpenguins::penguins |>
  dplyr::filter(!is.na(sex)) |>
  # criar uma coluna com a média por espécie e sexo
  dplyr::mutate(
    group_median_bill_length = median(bill_length_mm),
    .by = c(species, sex)
  ) |> 
  dplyr::mutate(
    # ajustar a ordem das espécies de acordo com a média calculada
    species = forcats::fct_reorder(
      species,
      group_median_bill_length,
      # cricar uma função customizada para garantir que a ordem seja correta,
      # essa função calcula a diferença entre os valores únicos da coluna
      # 'group_median_bill_length' e depois realiza o módulo dos mesmos
      .fun = \(x) unique(x) |> diff() |> abs()
    )
  )

penguins |>    
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  ggplot2::geom_point(
    size = 3,
    alpha = 0.75,
    shape = 21,
    color = "black",
    position = ggplot2::position_jitterdodge(seed = 34543)
  ) +
  ggplot2::theme_minimal(base_size = 16) +
  ggplot2::labs(
    x = ggplot2::element_blank(),
    y = "Comprimento do bico",
    fill = "Sexo",
    title = "Medições de diferentes espécies de pinguins"
  ) +
  ggplot2::scale_fill_discrete(labels = \(x) stringr::str_to_title(x)) +
  ggplot2::scale_y_continuous(labels = scales::label_number(suffix = "mm"))


```


## Lesson 6 - Active titles and text styling
```{r}

caption_text <- "Espécies foram ranqueadas pela diferença na média dos comprimentos dos bicos entre sexos. \n Dados obtidos pelo pacote R {palmerpenguins}."

penguins |>    
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = species,
      y = bill_length_mm,
      fill = sex
    )
  ) +
  ggplot2::geom_point(
    size = 3,
    alpha = 0.75,
    shape = 21,
    color = "black",
    position = ggplot2::position_jitterdodge(seed = 34543)
  ) +
  ggplot2::theme_minimal(
    base_size = 16,
    base_family = "Source Sans Pro" # trocando a fonte de texto do gráfico
  ) +
  # alterar elementos gerais do gráficos
  ggplot2::theme(
    plot.title.position = "plot", # alinhar título com a borda total do gráfico
    plot.caption.position = "plot", # alinhar nota de rodapé com a borda total do gráfico
    text = ggplot2::element_text(color = "grey20"), # alterar a cor do text no gráfico
    plot.title = ggplot2::element_text(lineheight = 1), # aumentar o espaço entre as linhas do título
    plot.subtitle = ggplot2::element_text(
      # aumentar o espaço entre o subtítulo e o título
      margin = ggplot2::margin(t = 4, b = 2, unit = "mm")
    ),
    # ajustar tamanho da nota de rodapé configurando para ser 60% do tamanho padrão do gráfico (base_size)
    plot.caption = ggplot2::element_text(size = ggplot2::rel(0.6))
  ) +
  ggplot2::labs(
    x = ggplot2::element_blank(),
    y = ggplot2::element_blank(), # remover o título do eixo y
    subtitle = "Comprimento do bico", # adicionar o título do eixo y como subtítulo para ficar na horizontal (mais fácil para ler)
    fill = "Sexo",
    # adicionando um título ATIVO, que transmite algo direto em sua leitura
    title = "Pinguins Chinstrap possuem a maior diferença \n no comprimento dos bicos entre sexos",
    # adicionar uma nota de rodapé
    caption = caption_text
  ) +
  ggplot2::scale_fill_discrete(labels = \(x) stringr::str_to_title(x)) +
  ggplot2::scale_y_continuous(labels = scales::label_number(suffix = "mm"))


```
